### ISSUE TITLE
Django 1.11 prohibites non-dict context

### ISSUE THREAD

**Issue by AlvaroLQueiroz** [django-haystack/django-haystack#1509] opened 2017-05-22 22:43 UTC
* [x] Tested with the latest Haystack release
* [x] Tested with the current Haystack master branch

The newest django releases prohibit no-dict context on __django.template.backends.django.Template.render()__

[Django releases](https://docs.djangoproject.com/en/1.11/releases/1.11/#django-template-backends-django-template-render-prohibits-non-dict-context)

**Comment by rijkstofberg** [comment] 2017-05-24 19:33
Looks like the fix for the script `build_solr_schema.py` is trivial.  Just return a dictionary not a Context instance.

**Comment by acdha** [comment] 2017-05-24 19:49
This is much simpler that we no longer need to support older versions of Django.

#1504 has this and a number of other modernization fixes about ready to merge. If you have time, please test that branch.

**Comment by RabidCicada** [comment] 2017-05-25 11:34
@AlvaroLQueiroz Can you See if this fixes your issues?  I believe the #1504 changes fix everything as @acdha has suggested.  But I'd like to see you close your own ticket if it's been addressed.

**Comment by AlvaroLQueiroz** [comment] 2017-06-02 03:51
@RabidCicada @acdha sorry for the delay.

#1504 fixed the execution of the command, but the tests and the docs has some problems yet.
[here](https://github.com/django-haystack/django-haystack/blob/master/test_haystack/solr_tests/test_templatetags.py#L20)
[here](https://github.com/django-haystack/django-haystack/blob/master/test_haystack/test_templatetags.py#L26)
and the [docs](https://github.com/django-haystack/django-haystack/blob/master/docs/rich_content_extraction.rst)

**Comment by acdha** [comment] 2017-06-02 13:37
@alvarolqueiroz: have you actually tested that? Django is inconsistent about when you need a Context (Django Template instances require it, the generic interfaces do not as you could be using a different templating system) and the other pull request which changed everything caused those tests to fail.

**Comment by acdha** [comment] 2017-06-15 15:02
Closing - if someone has a reproducible test case which fails against the current master branch please re-open

**Closed by acdha** 2017-06-15 15:02 UTC

**Comment by nobodyman** [comment] 2017-07-13 00:02
Would it be possible to add Django v1.11 to the testing suite? The current tox.ini appears to go up to v1.10. 

I'm also experiencing this error when trying to run `build_solr_schema` with  Django v1.11 and Haystack v2.6.1.

**Comment by acdha** [comment] 2017-07-13 01:04
@nobodyman it's already enabled for Travis if you want to send a pull request adding it to tox. Django 1.11 should work if you use the master branch – I'm hoping to ship a 2.7 beta now that more people have tested it
