### ISSUE TITLE
Key error u'_source' when searching

### ISSUE THREAD

**Issue by jlariza** [django-haystack/django-haystack#1307] opened 2016-02-04 21:40 UTC
Hello,

I'm having this issue when I'm trying to search for something. The update_index command is working fine and it is indexing the instance of my model.

The problem is that when I search something, I get KeyError u'_source'. Using Django Debug, I see the problem is at haystack/backends/elasticsearch_backend.py/ _process_results at line 
source = raw_result['_source']

At my context I have `raw_result =
{u'_id': u'properties.property.1',
 u'_index': u'haystack',
 u'_score': 0.191783,
 u'_type': u'modelresult'}`

So the Key error appears. Somebody knows how to fix it and make it works?

Thank you

**Comment by jlariza** [comment] 2016-02-05 13:45
I already found the error,  it was raised when calling the functions ``.values()`` or ``values_list()`` (I tried them both) I am using haystack 2.4.1. To solve it, I organized manually the data at returned by ``get_results()`` 

Thank you

**Comment by acdha** [comment] 2016-02-05 15:12
Can you test this using the current master branch? This looks like the same issue as #1019.

**Comment by SteveByerly** [comment] 2016-07-10 22:35
duplicate of #1019 which seems to have been fixed

**Closed by SteveByerly** 2016-07-10 22:35 UTC
