### ISSUE TITLE
views_and_forms.rst change page_object to page_obj

### ISSUE THREAD

**Issue by xgeetx** [django-haystack/django-haystack#1229] opened 2015-07-19 20:37 UTC
Documentation says that when migrating to new generic_views you must change "page" in your template to "page_object". It is actually "page_obj".

**Comment by alimony** [comment] 2015-12-14 14:55
This seems to be a duplicate of this later issue that has been resolved:

https://github.com/django-haystack/django-haystack/pull/1263

**Closed** 2016-01-18 16:37 UTC
