### ISSUE TITLE
ImportError: cannot import name 'six'

### ISSUE THREAD

**Issue by meetsl** [django-haystack/django-haystack#1709] opened 2020-01-13 04:00 UTC
|Package |Version|
|---|---|
Django | 3.0.1  
django-haystack | 2.8.1  
jieba | 0.41   
Whoosh | 2.7.4
Python | 3.6.9

#### Exception:
```
   File "~/.virtualenvs/env1/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "~/.virtualenvs/env1/lib/python3.6/site-packages/haystack/__init__.py", line 11, in <module>
    from haystack.utils import loading
  File "~/.virtualenvs/env1/lib/python3.6/site-packages/haystack/utils/__init__.py", line 9, in <module>
    from django.utils import six
ImportError: cannot import name 'six'
```

**Comment by acdha** [comment] 2020-01-13 15:07
This is a duplicate of #1702

**Closed** 2020-01-13 15:07 UTC

**Comment by RomanAVolodin** [comment] 2020-07-04 22:51
> This is a duplicate of #1702

So ? #1702 goes here. The loop is closed without any decision.

**Comment by acdha** [comment] 2020-07-04 22:54
The fix was merged so both are closed
