### ISSUE TITLE
update_index's batched slice requeries can be very slow with large OFFSETs

### ISSUE THREAD

**Issue by gojomo** [django-haystack/django-haystack#1077] opened 2014-09-24 22:53 UTC
Was using rebuild_index on a model with ~7 million small instances, in 10K batches, from a postgres database (specifically Heroku's standard-0). At about the 3.1 million mark, the batch-fetch queries became incredibly slow: ~500secs instead of ~12secs – changing an 'hours' job to 'days or weeks'. Other followup testing & research suggest: the slice-generated OFFSET queries will often be relatively slow, compared to two other potential approaches. (Another risk: table changes between slices could lead to inconsistent batch boundaries, missing or redundantly indexing docs.)

One possible alternative: query performance might improve if refactored to remember last pk of previous batch, use as lower-bound of next batch. (Easier in single-process case.)

Second possible alternative (the route I took): refactoring update_index to use the no-Django-caching QuerySet.iterator(), and no-psycopg2-caching server_side_cursors() from djorm-ext-core. This allows iterating over all rows from a single query, without using unbounded memory, while still batching to the backend. Code can be viewed here: https://github.com/gojomo/django-haystack/commit/db4a71ff0220633028af6ca2a14cc7ccffc36e89 – succeeded in doing ~7 million model index with negligible slowdown for later batches. 

Project might not want this postgres-specific, server_side_cursors()-dependent approach but thought I'd drop a description of the performance issue and possible solution here for future reference.

**Comment by AdrianLC** [comment] 2015-11-12 14:58
Can confirm this.
Rebuilding or big updates become quite slow even with just a million rows, specially if the table is being read from the admin or somewhere else simultaneously.

There's a good explanation on why big offsets are slow [here](http://stackoverflow.com/questions/26625614/select-query-with-offset-limit-is-too-much-slow#answer-27169302). Replacing the offsets with intervals of ids could be an appropriate solution. At least while django does not support server side cursors: https://code.djangoproject.com/ticket/16614

**Comment by mjl** [comment] 2017-02-06 11:08
I can confirm this happens with Postgres as a database.

I'm currently trying to implement a partial fix, will comment later when I have more data. It's a bit of a slow process since every test takes about an hour.

**Comment by mjl** [comment] 2017-02-06 13:17
Here's my blurb with some details and timings for the above commit, in case someone stumbles over this issue and wonders why this happens.

Rebuilding an index with Postgres sees very slow performance once one
there are more than a handful of entries to index (a handful is about 
100k in this context).

The current code causes queries like:

	SELECT ... FROM ... ORDER BY pk ASC LIMIT 1000 OFFSET 897000

which take longer the larger the offset is. The above took about 5s
on my test installation.

The performance also depends on Postgres' ```effective_cache_size``` parameter.
If this is set to a too small value, the postgres optimizer will start
to use temporary tables for the above queries, which slows them down
even more.

As a baseline, the rebuild_index for my test data set for about 1M entries:

	$ time python manage.py rebuild_index -v2 --noinput
	Removing all documents from your index because you said so.
	All documents removed.
	Indexing 1027471 KIT+ customers
	...
	real	66m23.400s
	user	9m53.027s
	sys	0m12.732s

The modified code does the following:

* return the largest PK seen from ```management.commands.update_index.do_update()```
* pass the PK in to the next iteration of ```do_update()```
* use a ```qs.filter(pk__gte=max_pk)[:batch_size]``` instead of ```qs[start:end]```.

This makes postgres to always use the index on PK and not use a
temporary file, resulting in about constant query time (~200msec).

Note that this only modifies the synchronous update path, not the
multithreading worker updates, since I cannot easily pass the last
seen pk to the next batch worker.

Timing results with the modified code:

	$ time python manage.py rebuild_index -v2 --noinput
	Removing all documents from your index because you said so.
	All documents removed.
	Indexing 1027471 KIT+ customers
	...
	real	17m36.026s
	user	9m48.805s
	sys	0m12.385s

**Comment by acdha** [comment] 2017-02-06 14:57
@mjl This is a problem as generic solution since Haystack doesn't require primary keys to be numeric but since it's so dramatic I'm wondering whether it might be useful to have this as a special-case optimization when the pk type isn't something like a UUID.

**Comment by mjl** [comment] 2017-02-06 15:29
The solution doesn't really assume anything about the PK, it should work just as well with guid or strings or dates or whatnot. All it needs is to have the PK orderable by the database -- which must be possible anyway otherwise it couldn't do an ORDER BY on it.

**Comment by mjl** [comment] 2017-02-14 08:34
Here a real world data point, I rolled out my branch to our production site and this is before:

     2017-02-08 03:53:15 Starting re-index (local)
     Indexing 1027196 customers
     2017-02-08 04:30:59 Indexing complete

And after:

     2017-02-14 03:51:06 Starting re-index (local)
     Indexing 1027071 customers
     2017-02-14 04:01:00 Indexing complete

**Comment by mjl** [comment] 2017-06-07 08:20
@acdha Any idea on how to move this forward? I see #1514, which does basically the same AFAICT.

I still believe that this should work fine with whatever type the PK is, but we could make it optional if you fear interop problems with weird data models.

**Comment by acdha** [comment] 2017-06-07 17:08
@mjl I'm inclined to just merge it now and focus on reviewing the other changes in @ggaughan's #1514 and confirming that we have solid test coverage for this change before the next release.

**Comment by mjl** [comment] 2017-06-07 17:10
Yeah! Anything I can do to make life easier for you?

**Comment by acdha** [comment] 2017-06-07 17:11
If you could send a PR which is rebased on the current master branch that's the easiest thing for me to review but this isn't exactly a massive amount of code to pull forward

**Comment by mjl** [comment] 2017-06-07 17:25
Updated the pull request, it merged cleanly, no problems.

**Comment by Mariownyou** [comment] 2022-07-30 11:31
How to efficiently rebuild indexes for large database, 5-6 million rows? ‘rebuild_index’ works very slow, and there’s no indexation of process

**Comment by acdha** [comment] 2022-07-30 12:39
> How to efficiently rebuild indexes for large database, 5-6 million rows? ‘rebuild_index’ works very slow, and there’s no indexation of process

This is probably a separate discussion from this issue. In general, you’d want to run with a sufficient verbosity level to see where the slowdown is. It could be that you need to increase the batch size or enable concurrency. In other cases, you might need to enable some of the Django ORM prefetching in the query set you’re using for indexing to avoid O(N) queries looking up related field values on every record. This issue also highlights that you might need to tweak your ordering if the queries you’re making are forcing the database to do more work.

**Closed by acdha** 2022-07-30 12:39 UTC
Labels: needs review
