### ISSUE TITLE
install failure: ERROR: Requested django-haystack==3.0 ... has different version in metadata: '0.0.0'

### ISSUE THREAD

**Issue by bcail** [django-haystack/django-haystack#1753] opened 2021-01-08 18:09 UTC
* [x] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

I'm trying to pip install django-haystack - pip finds 3.0 as the latest version, but then fails to install it.

## Expected behaviour
successful install of django-haystack 3.0

## Actual behaviour
$ pip install django-haystack
Collecting django-haystack
  Using cached django-haystack-3.0.tar.gz (450 kB)
ERROR: Requested django-haystack from https://files.pythonhosted.org/packages/1b/2d/dd6ca8ada77e8d646dcbe847cebf8d3769c2dc9906a38800fde1b90f0a55/django-haystack-3.0.tar.gz#sha256=d490f920afa85471dd1fa5000bc8eff4b704daacbe09aee1a64e75cbc426f3be has different version in metadata: '0.0.0'
(package doesn't get installed)
Note: I think in previous versions of pip, it installs django-haystack and shows the version as 0.0.0.

## Steps to reproduce the behaviour

1. pip install django-haystack (with latest version of pip)

## Configuration

* Operating system version: RHEL 7
* Search engine version: n/a
* Python version: cpython 3.6.1
* Django version: 2.2.16
* Haystack version: 3.0

**Comment by acdha** [comment] 2021-01-08 21:33
Here's what it looks like on a clean install — I'm not sure whether this is something with the RHEL packages, version of pip, etc. 

```bash
$ docker run -it python:3.9 pip install django-haystack
Collecting django-haystack
  Downloading django-haystack-3.0.tar.gz (450 kB)
     |████████████████████████████████| 450 kB 471 kB/s 
Collecting Django>=2.2
  Downloading Django-3.1.5-py3-none-any.whl (7.8 MB)
     |████████████████████████████████| 7.8 MB 1.3 MB/s 
Collecting sqlparse>=0.2.2
  Downloading sqlparse-0.4.1-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 330 kB/s 
Collecting asgiref<4,>=3.2.10
  Downloading asgiref-3.3.1-py3-none-any.whl (19 kB)
Collecting pytz
  Downloading pytz-2020.5-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 2.2 MB/s 
Building wheels for collected packages: django-haystack
  Building wheel for django-haystack (setup.py) ... done
  Created wheel for django-haystack: filename=django_haystack-3.0-py3-none-any.whl size=135114 sha256=03269f2a553e8c70268908d301653331e8dcd48afc02d166bed5f95e4a56588b
  Stored in directory: /root/.cache/pip/wheels/79/ff/09/5b685cfb60b0d02ab455d5d7e035e5f5d74243b91f33cb8ad5
Successfully built django-haystack
Installing collected packages: sqlparse, asgiref, pytz, Django, django-haystack
Successfully installed Django-3.1.5 asgiref-3.3.1 django-haystack-3.0 pytz-2020.5 sqlparse-0.4.1
WARNING: You are using pip version 20.2.4; however, version 20.3.3 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```

```bash
$ docker run -it python:3.6 pip install django-haystack
Unable to find image 'python:3.6' locally
3.6: Pulling from library/python
6c33745f49b4: Already exists 
ef072fc32a84: Already exists 
c0afb8e68e0b: Already exists 
d599c07d28e6: Already exists 
f2ecc74db11a: Already exists 
0e7ac7e3db3f: Pull complete 
dfd5461cd34f: Pull complete 
e6a2d3233da5: Pull complete 
099a5f6e48a0: Pull complete 
Digest: sha256:4c00d277e8c189175dc460419e17049b98d7d93dd3021700ddb8400646bbc50a
Status: Downloaded newer image for python:3.6
Collecting django-haystack
  Downloading django-haystack-3.0.tar.gz (450 kB)
     |████████████████████████████████| 450 kB 586 kB/s 
Collecting Django>=2.2
  Downloading Django-3.1.5-py3-none-any.whl (7.8 MB)
     |████████████████████████████████| 7.8 MB 1.1 MB/s 
Collecting asgiref<4,>=3.2.10
  Downloading asgiref-3.3.1-py3-none-any.whl (19 kB)
Collecting sqlparse>=0.2.2
  Downloading sqlparse-0.4.1-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 347 kB/s 
Collecting pytz
  Downloading pytz-2020.5-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 2.2 MB/s 
Building wheels for collected packages: django-haystack
  Building wheel for django-haystack (setup.py) ... done
  Created wheel for django-haystack: filename=django_haystack-3.0-py3-none-any.whl size=135116 sha256=963882a14fea95c51aa5df45d1bc8eeae42612207524c12a4343d3fba05a2a65
  Stored in directory: /root/.cache/pip/wheels/9d/6a/b2/dae3996988e6bbfb4b1e3a85956a5391b9f2ec2d1eed35e945
Successfully built django-haystack
Installing collected packages: sqlparse, pytz, asgiref, Django, django-haystack
Successfully installed Django-3.1.5 asgiref-3.3.1 django-haystack-3.0 pytz-2020.5 sqlparse-0.4.1
```

**Comment by acdha** [comment] 2021-01-08 21:35
The SHA-256 hashes match, too, so I'm using the same tarball as your example above.

**Comment by bcail** [comment] 2021-01-11 14:09
OK, looks like it may be related to this code (in haystack/\_\_init\_\_.py):
```
try:
    pkg_distribution = get_distribution("django-haystack")
    __version__ = pkg_distribution.version
    version_info = pkg_distribution.parsed_version
except DistributionNotFound:
    __version__ = "0.0.dev0"
    version_info = parse_version(__version__)
```

My setuptools version was 28.8.0, and after upgrading setuptools to 51.1.2, haystack installed fine.

**Comment by claudep** [comment] 2022-02-05 22:20
setuptools 28.8.0 was released in 2016, so I don't think we should do anything here.

**Closed by claudep** 2022-02-05 22:20 UTC

**Comment by chipx86** [comment] 2024-07-31 03:26
For anyone else who might find this ticket while hitting this with a modern setuptools, I'd like to provide some additional findings.

We hit this same error in modern versions of Haystack (3.2.1 and 3.3), and the fault was traced to a combination of:

1. `setuptools-scm`'s logic to look in the current source tree for version information, and:
2. Attempting to build this in an environment within a separate source tree, with:
3. An explicit Haystack version number or range that does not include 0.0.0.


## Repro Case

An easy way to reproduce this is:

1. Activate a virtualenv, if you want.
2. Create a blank Git repository: `git init /tmp/ticket1753`
3. `cd /tmp/ticket1753`
4. `pip install --no-build-isolation django-haystack==3.3.0`

Result:

```
Collecting django-haystack==3.3.0
  Downloading django_haystack-3.3.0.tar.gz (467 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 467.3/467.3 kB 8.5 MB/s eta 0:00:00
  Preparing metadata (pyproject.toml) ... done
  WARNING: Requested django-haystack==3.3.0 from https://files.pythonhosted.org/packages/b4/09/623634ca5f8b9fe99d07d284491724eb1b0704022e942a1fe815c1d13a02/django_haystack-3.3.0.tar.gz, but installing version 0.0.0
Discarding https://files.pythonhosted.org/packages/b4/09/623634ca5f8b9fe99d07d284491724eb1b0704022e942a1fe815c1d13a02/django_haystack-3.3.0.tar.gz (from https://pypi.org/simple/django-haystack/): Requested django-haystack==3.3.0 from https://files.pythonhosted.org/packages/b4/09/623634ca5f8b9fe99d07d284491724eb1b0704022e942a1fe815c1d13a02/django_haystack-3.3.0.tar.gz has inconsistent version: expected '3.3.0', but metadata has '0.0.0'
ERROR: Could not find a version that satisfies the requirement django-haystack==3.3.0 (from versions: 1.0.0-final, 1.0.1-final, 1.0.2-final, 1.0.0rc1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2, 2.4.0rc1, 2.4.0rc2, 2.4.0, 2.4.1, 2.5.dev0, 2.5.dev1, 2.5.dev2, 2.5.0, 2.5.1, 2.6.0, 2.6.1, 2.7.dev0, 2.7.dev1, 2.7.0, 2.8.0, 2.8.1, 3.0b1, 3.0b2, 3.0, 3.1.0, 3.1.1, 3.2.dev0, 3.2.0, 3.2.1, 3.3b2, 3.3.0)
ERROR: No matching distribution found for django-haystack==3.3.0
```

## Why this happens

`setuptools-scm` looks for a branch or tag it can use as a base for the version. If the logic runs while inside an existing Git or Mercurial tree, it will refer to the branches/tags there, with the assumption that this is the project root, and fall back to `haystack/version.py` if it fails to find a match.

That works great if it is in fact the project root within the official Haystack tree, or if running the packaging mechanisms through a standard isolated build environment.

It won't work in the following situations:

1. Installing without build isolation (`--no-build-isolation`).

   While not particularly common, it can happen for more complicated build environments that need to refer to local files/state that can't be placed in an isolated build environment and should instead be built within the active source tree.

2. Including Haystack within another source tree.

   If, as part of build management, you were to track stable versions of Haystack and other projects within a source tree, the version information would fail. This is more hypothetical in my case, but I've seen this pattern before.

"Don't do that." Yeah, I don't disagree, but there are sometimes reasons. Currently, the only dependency we've encountered that breaks in this form of environment is Haystack.

It may not be an important thing for Haystack to address, but I feel that knowing the reasons this may happen is important.


## Possible Resolutions

1. Ship wheels.

   Ideally, Haystack would be available as pre-built wheels. That's less that the consuming end must do to handle installation, and it's faster to install. It also ensures there's exactly one official version of a build for any version of Haystack. And, of course, it avoids the side effect issues that can be found with a non-isolated build environment.

2. Manage versions manually.

   By updating `haystack/version.py` manually, instead of using `setuptools-scm` to manage it, you completely avoid the side-effects in `setuptools-scm`. Then it doesn't matter what the build environment looks like, or how people are attempting to interact with/track the package.

I would *love* to see wheels, at a minimum, as that would address some of the problems we hit and make it easier for us to provide more easily-reproduceable build environments that consist of Haystack. Not having to worry about the quirks of `setuptools-scm` would be nice, too.

Anyway, I hope that's helpful to anyone who may hit this problem, Googling in frustration and confusion as to why `pip` says it can't find a particular version and then lists that version in the candidates, and ends up finding this ticket.
