### ISSUE TITLE
Error when removing stale records - AttributeError: Nonetype object has no attribute '_meta'

### ISSUE THREAD

**Issue by anuragjain** [django-haystack/django-haystack#1387] opened 2016-06-24 14:07 UTC
* [x] Tested with the latest Haystack release

## Expected behaviour
Objects should get removed from index
## Actual behaviour
Getting AttributeError: Nonetype object has no attribute '_meta'

removing 1 stale records.
ERROR Error updating analytics using default 
Traceback (most recent call last):
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
self.update_backend(label, using)
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 289, in update_backend
backend.remove(rec_id, commit=self.commit)
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 199, in remove
doc_id = get_identifier(obj_or_string)
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/utils/init.py", line 37, in default_get_identifier
return u"%s.%s" % (get_model_ct(obj_or_string),
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/utils/init.py", line 81, in get_model_ct
return "%s.%s" % get_model_ct_tuple(model)
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/utils/init.py", line 75, in get_model_ct_tuple
return (model.meta.app_label, model.meta.model_name)
AttributeError: 'NoneType' object has no attribute '_meta'
Traceback (most recent call last):
File "./manage.py", line 10, in 
execute_from_command_line(sys.argv)
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/django/core/management/__init.py", line 354, in execute_from_command_line
utility.execute()
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/django/core/management/init.py", line 346, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
self.execute(args, *cmd_options)
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
output = self.handle(args, *options)
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 183, in handle
return super(Command, self).handle(items, *options)
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/django/core/management/base.py", line 623, in handle
label_output = self.handle_label(label, **options)
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
self.update_backend(label, using)
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 289, in update_backend
backend.remove(rec_id, commit=self.commit)
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 199, in remove
doc_id = get_identifier(obj_or_string)
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/utils/init.py", line 37, in default_get_identifier
return u"%s.%s" % (get_model_ct(obj_or_string),
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/utils/init.py", line 81, in get_model_ct
return "%s.%s" % get_model_ct_tuple(model)
File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/utils/init.py", line 75, in get_model_ct_tuple
return (model._meta.app_label, model._meta.model_name)
AttributeError: 'NoneType' object has no attribute '_meta'

## Steps to reproduce the behaviour

1.Build Full index
2.Manually remove from database
3.Update index with remove parameter

This is my index definition for reference

    class ProductViewIndex(indexes.SearchIndex, indexes.Indexable):
	   text = indexes.CharField(document=True, use_template=True)
	   ProductViewId = indexes.IntegerField(model_attr='id', indexed=True, stored=True)
	   productName = indexes.CharField(model_attr='getProductName', indexed=True, stored=True)
	   userId = indexes.IntegerField(model_attr='getUserId', indexed=True, stored=True, null=True)
	   sessionKey = indexes.CharField(model_attr='getSessionKey', indexed=True, stored=True, null=True)
	   count = indexes.IntegerField(model_attr='count', indexed=True, stored=True)

	def get_model(self):
		return ProductView

## Configuration

* Operating system version: OS X El Capitan - 10.11.5
* Search engine version: ElasticSearch version 1.7.5, with elastic search binding version 1.7.0
* Python version:2.7.10
* Django version:1.8.11
* Haystack version:2.4.1

**Comment by acdha** [comment] 2016-06-24 14:30
Duplicate of #1380

**Closed by acdha** 2016-06-24 14:30 UTC

**Comment by anuragjain** [comment] 2016-06-24 14:40
@acdha This is not duplicate as in the other question, I was asked to downgrade the elastic search version which I did. Right now I am using elastic search version of 1.7.5

**Comment by acdha** [comment] 2016-06-24 14:45
It's the same error, though, so we should keep the discussion in the same place.

**Comment by anuragjain** [comment] 2016-06-24 14:47
@acdha I commented that I am getting the same error even after downgrading but didn't get any response, so opened a new issue.
I should have tagged you, my bad.
