### ISSUE TITLE
Cut Django 1.9 compatible release?

### ISSUE THREAD

**Issue by ryanmrubin** [django-haystack/django-haystack#1370] opened 2016-05-20 15:26 UTC
Other issues (e.g. #1300 ) suggest that master is compatible with Django 1.9, but 2.4.1 is still not. I tried contacting via other means first, but wanted to see: is there a timeline for when we should expect a Django 1.9-compatible release?

**Comment by acdha** [comment] 2016-05-27 19:39
2.5.dev1 is on pypi now for testing

**Comment by mvantellingen** [comment] 2016-07-11 12:57
Hi @acdha, what are the next steps to get a 2.5.0 release on pypi? Django Oscar is currently blocked due to this (http://github.com/django-oscar/). If there are only minor issues to be resolved with which we can help then please let me know.

**Comment by acdha** [comment] 2016-07-11 13:05
It's mostly been testing - I've been busy with other things lately and didn't want to publish a release before dropping out of contact.
I think by now enough people have confirmed that it's working for them that I'd be comfortable releasing it this week.

**Comment by mvantellingen** [comment] 2016-07-11 13:32
Thanks for the quick reply, great to hear  👍

**Comment by acdha** [comment] 2016-07-11 14:17
If anyone watching this issue has not had time to install v2.5.dev2, please do so (e.g. `pip install django-haystack==2.5.dev2`) and let me know if you encounter any problems.

**Comment by acdha** [comment] 2016-07-12 16:02
As of a couple seconds ago, 2.5.0 is on PyPI

**Closed by acdha** 2016-07-12 16:02 UTC
