### ISSUE TITLE
AttributeError at /search/  'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by jranand** [django-haystack/django-haystack#1200] opened 2015-05-24 14:00 UTC
Request Method: 	GET
Request URL: 	http://localhost:8000/search/?q=Hello
Django Version: 	1.8.1
Exception Type: 	AttributeError
Exception Value: 	

'list' object has no attribute 'split'

Exception Location: 	/usr/local/lib/python2.7/dist-packages/haystack/backends/solr_backend.py in _process_results, line 374
Python Executable: 	/usr/bin/python
Python Version: 	2.7.8
Python Path: 	

['/home/jr/everscoop_search',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']

app_label, model_name = raw_result[DJANGO_CT].split(".")

I am Using Django 1.8.1 Kindly Help me with issue.

**Comment by monkeypants** [comment] 2015-06-15 06:09
This is biting me too, using solr 5.2, django 1.8, and current django-haystack (with pip).  In /backends/solr_backend.py, I see:

    378:        for raw_result in raw_results.docs:
    379:            app_label, model_name = raw_result[DJANGO_CT].split('.')
    380:            additional_fields = {}
    381:            model = haystack_get_model(app_label, model_name)

But when I query solr through the admin API, when I look at the response part of the returned json, I see that django_ct object is indeed a list:

    "django_ct": ["my_app_label.my_model_name",]

So, what's the bug?
 * should the solr backend be iterating over a this list (rather than trying to access it as a string)?
 * should the solr backend gracefully deal with strings or lists of strings?
 * something wrong with how the solr index is being populated?

**Comment by monkeypants** [comment] 2015-06-15 06:32
Maybe also relevant, either with django1.8 or downgrading to django 1.7.7, `manage.py build_solr_schema` generates the following field specifications:

    <field name="django_ct" type="string" indexed="true" stored="true" multiValued="false"/>
    <field name="django_id" type="string" indexed="true" stored="true" multiValued="false"/>

and even after downgrading to django 1.7.7 and doing a `manage.py rebuild_index`, both django_ct and django_id returned as "lists of one value" by solr.

**Comment by acdha** [comment] 2015-06-15 14:43
Closing as a duplicate of #1182. The fix will require updating to handle the backwards-incompatible change in Solr 5.

**Closed by acdha** 2015-06-15 14:43 UTC
Labels: Dependency Updates

**Comment by krmritunjay11** [comment] 2018-03-13 09:16
After 3-4 days I reached at solution.

**Step1:** Go to your collection managed-schema file and edit
**Step2 :** Find and replace <field name="django_ct" type="**text_general**"/> to <field name="django_ct" type="**string**"/>

- Operating system version: Ubuntu 14.04 LTS
- Search engine version: Solr 7.2.1
- Python version: 3.4.3
- Django version: 2.0
- Haystack version: 2.8.0

**Comment by acdha** [comment] 2018-03-16 15:41
@krmritunjay11 Do you have any idea what changed your django_ct schema from the standard Haystack default?

**Comment by FelixSebastianLange** [comment] 2018-07-17 14:43
To elaborate on what @mjwalter , writes, after some tests with different versions (no such error with solr 6.x),  I conclude the that  haystack does not fully support Solr  7.x . The Django Version should not matter here. An example stack-trace:
`File "/Users//dev//theApp/forms.py", line 129, in search
    sqs.count()
  File "/Users//dev/virtual_envs/venv36/lib/python3.6/site-packages/haystack/query.py", line 522, in count
    return len(self)
  File "/Users//dev/virtual_envs/venv36/lib/python3.6/site-packages/haystack/query.py", line 86, in __len__
    self._result_count = self.query.get_count()
  File "/Users//dev/virtual_envs/venv36/lib/python3.6/site-packages/haystack/backends/__init__.py", line 619, in get_count
    self.run()
  File "/Users//dev/virtual_envs/venv36/lib/python3.6/site-packages/haystack/backends/solr_backend.py", line 802, in run
    results = self.backend.search(final_query, **search_kwargs)
  File "/Users//dev/virtual_envs/venv36/lib/python3.6/site-packages/haystack/backends/__init__.py", line 33, in wrapper
    return func(obj, query_string, *args, **kwargs)
  File "/Users//dev/virtual_envs/venv36/lib/python3.6/site-packages/haystack/backends/solr_backend.py", line 149, in search
    distance_point=kwargs.get('distance_point'))
  File "/Users//dev/virtual_envs/venv36/lib/python3.6/site-packages/haystack/backends/solr_backend.py", line 425, in _process_results
    app_label, model_name = raw_result[DJANGO_CT].split('.')
AttributeError: 'list' object has no attribute 'split'`

**Comment by nwself** [comment] 2018-11-01 15:43
I had this problem with 

- Operating system version: Ubuntu 18.04 LTS
- Search engine version: Solr 6.6.5
- Python version: 3.6.6
- Django version: 2.0.8
- Haystack version: 2.8.1

Solved it with
```
solr stop
rm <solr_home>/server/solr/<core>/conf/managed-schema
./manage.py build_solr_schema > <solr_home>/server/solr/<core>/conf/schema.xml
solr start
./manage.py rebuild_index
```

Not sure how much of that was necessary but that solved it.

**Comment by daxaxelrod** [comment] 2019-05-10 20:47
Happening for me while using solr 8.0. @krmritunjay11 modifying the site package works for me but I just wanted to put this out there.

my schema already had django_ct as a `<field name="django_ct" type="string" indexed="true" stored="true" multiValued="false"/>` and it comes directly from the management command

**Comment by rifuso** [comment] 2019-10-23 23:55
Similar to what others reported, I had to make a couple changes to solr_backed.py. changing both [DJANGO_ID] to [DJANGO_ID][0] and [DJANGO_CT] to [DJANGO_CT][0]. The schema.xml file required no changes.

Using Solr 8.2.0, Django 2.2.6 and Haystack 2.8.1.

**Comment by JohnMulligan** [comment] 2023-04-12 09:45
Hi folks, was this ever actually fixed? [Neither the master branch nor PR 1828](https://github.com/django-haystack/django-haystack/pull/1828#ref-commit-ad690bd) seem to resolve the issue above. I have to keep making this patch to solr_backend.py.

Using
pysolr==3.9.0
django-haystack==3.2.1
django==4.2

Solr 8.5.2
