### ISSUE TITLE
rebuild_index() not working with Django 2.*

### ISSUE THREAD

**Issue by JonLevischi** [django-haystack/django-haystack#1592] opened 2018-03-02 15:49 UTC
* [x] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behaviour
Rebuild index for old entries, only new one are being registered on the database.

## Actual behaviour
Throwing the following error:
TypeError: Unknown option(s) for clear_index command: batchsize, workers. Valid options are: commit, help, interactive, no_color, nocommit, noinput, pythonpath, settings, skip_checks, stderr, stdout, traceback, using, verbosity, version.

## Steps to reproduce the behaviour

1. Open terminal, connect to server, run:
pip3 manage.py rebuild_index

## Configuration

* Operating system version: Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-48-generic x86_64) @ AWS
* Search engine version: Whoosh 2.7.4
* Python version: 3.5.1
* Django version: 2.0.2
* Haystack version: 2.7.0

**Comment by acdha** [comment] 2018-03-02 16:09
Duplicate of #1582. Can you test that branch and add your comments?

**Closed by acdha** 2018-03-02 16:09 UTC

**Comment by acdha** [comment] 2018-03-09 15:57
I just merged #1582 and tagged v2.8.0: https://pypi.python.org/pypi/django-haystack/2.8.0
