### ISSUE TITLE
Add ElasticSearch 2.0 support

### ISSUE THREAD

**Issue by auvipy** [django-haystack/django-haystack#1247] opened 2015-09-25 18:33 UTC
Elastic search 2.0 is in beta and used apache lucene. And should be added on future release of haystack

**Comment by hellysmile** [comment] 2015-11-12 00:21
https://www.elastic.co/guide/en/elasticsearch/reference/2.x/mapping-boost-field.html

mapping do not work with ES 2.0+

**Comment by mjl** [comment] 2015-11-17 14:54
Also faceting does not with with ES 2.0, it throws an exception on the ES side:

    SearchParseException[failed to parse search source. unknown search element [facets]]

According to this https://www.elastic.co/guide/en/elasticsearch/reference/current/search-facets-filter-facet.html facets have been removed.

**Comment by aldarund** [comment] 2015-11-29 11:15
+1. ES 2 not in beta anymore, but it doesnt work with haystack

**Comment by acdha** [comment] 2015-11-30 15:50
Is anyone on this ticket interested in helping work on a pull request for ES2 support? I don't use ElasticSearch much & the main project I use it with has not upgraded to 2.0 yet so my time to work on this is limited.

**Comment by barseghyanartur** [comment] 2015-12-04 13:30
+1

**Comment by auvipy** [comment] 2015-12-04 14:33
@acdha I am interested, any instructions?

**Comment by acdha** [comment] 2015-12-04 19:38
@auvipy Thanks! In general, I'd recommend starting work in a branch for the eventual pull request. If you haven't previously read through https://github.com/django-haystack/django-haystack/blob/master/CONTRIBUTING.md that's probably not a bad idea but there shouldn't be anything surprising in there. The main thing we'll need to figure out is what this will look like for backwards-compatibility – e.g. is it going to be hard to support both ES1 and ES2 in the same code-base.

**Comment by hanneman** [comment] 2015-12-04 19:49
:+1:

**Comment by barseghyanartur** [comment] 2015-12-05 06:33
I think it's better to have two separate back-ends: one for elastic search 1.x and another for 2.x.

**Comment by auvipy** [comment] 2015-12-05 10:04
yes the new back end should be separate one

**Comment by acdha** [comment] 2015-12-05 14:33
That will certainly make maintenance easier

**Comment by egolts** [comment] 2015-12-10 18:42
+1

**Comment by ytyng** [comment] 2015-12-29 10:44
+1

**Comment by nsoft-andrey** [comment] 2016-01-06 14:13
+1

**Comment by mmangione** [comment] 2016-01-09 17:47
+1

**Comment by acdha** [comment] 2016-01-11 14:52
Note to anyone leaving “+1” comments: please use the subscribe button on the right if you're not actually working on the ES2 backend.

**Comment by chocobn69** [comment] 2016-02-05 16:04
Someone is working on it ? I can try if I can find time @work

**Comment by auvipy** [comment] 2016-02-05 16:13
sorry I couldn't

**Comment by frague59** [comment] 2016-02-07 17:03
HI chocobn69, 

I've few ideas about stuff we could add for es 2.x support in haystack. I've monkey-patched my haystack for that, but my code is really specific for my project, so it can't be showed at this time.

About the settings : 

- Remove the _boost parameter sent to the es engine : not supported anymore, it crashes the index creation / upgrade
- Add support for mapper-attachments as fields (I've a good code base about that, I do almost understand now how it work... es docs are very fuzzy about that.)
except those, the es engine seems to work fine for me.

If you create a branch for this, I'll be happy to share my code about that, but I can't be the leader for this project (not many time to give for)

ES 2.x official support in haystack 'll be a god news !

**Comment by barseghyanartur** [comment] 2016-02-07 21:32
I can confirm, that _boost parameter should be removed. I have experienced same problem with running haystack on elasticsearch 2.x. With _boost parameter index would crush. Without it, it would just build, although more or less comlex queries, such as sorting on distance, would fail.

**Comment by chocobn69** [comment] 2016-02-08 09:37
Ok
I already did a branch on my fork (not pushed yet)
First, I will focuse on passing es1 tests (without facets and _boost)

**Comment by frague59** [comment] 2016-02-08 12:16
My code : WTFPL licence..

https://gist.github.com/frague59/8ab2470ed133754a6327

**Comment by LennyLip** [comment] 2016-02-17 09:17
Why we can not to use official low level client for python?
https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/index.html

And users can will be install  any version they want (add dependency 'elasticsearch' to django-haystack)

# Elasticsearch 2.x
elasticsearch>=2.0.0,<3.0.0

# Elasticsearch 1.x
elasticsearch>=1.0.0,<2.0.0

# Elasticsearch 0.90.x
elasticsearch<1.0.0

**Comment by PedroAquilino** [comment] 2016-03-23 15:35
I worked on a new backend for ES 2.x support.
Mainly I've cloned the ES 1.x code and tests and worked over that.
The changes are:
* facets (aggregations on ES 2.x)
* delete_by_query (scroll API and bulk actions on ES 2.x)
* "more like this" (More Like This Query)

The branch is passing tests. But I'm not sure if is ready for "pull request" (newbie here)
https://github.com/PedroAquilino/django-haystack/tree/es2

**Comment by chocobn69** [comment] 2016-03-23 15:38
great job ! I started the same, but didn't find the time to finish

hop it will be merge soon

**Comment by SalahAdDin** [comment] 2016-03-23 17:55
:+1:

**Comment by gfairchild** [comment] 2016-05-12 18:14
👍

**Comment by failedguidedog** [comment] 2016-05-25 07:53
+1

**Comment by acdha** [comment] 2016-05-25 12:51
Just a brief reminder: adding a 👍  doesn't do anything but give everyone another email to delete. Haystack is a volunteer project and if you use ElasticSearch the best way to get this feature to arrive is to help by reviewing and testing the code in https://github.com/django-haystack/django-haystack/issues/1336 and report your results there.

**Comment by nherriot** [comment] 2016-06-10 10:59
Hi all,
not wanting to clutter up the thread with crud. But I'm using hasystack and elastic for the www.alfa.com site. We are at the moment trying to move to ES.2.2 and seeing the same errors as you guys.

Would love to help and contribute. Who is leading? And what tasks can/should we be helping out with?

Kind regards, Nicholas.

**Comment by acdha** [comment] 2016-06-10 13:12
@nherriot Thanks for the offer – I would look at the code in #1336. My main projects all use Solr so my time to work on that is limited. @PedroAquilino has done most of the actual work.

**Comment by DilshadGit** [comment] 2016-06-10 22:04
I have used ES1.7 and update to 2.3.3 now got the same error. I am happy to see the codes to review and test.

Thanks
Dilshad

**Comment by Mibou** [comment] 2016-07-06 09:06
I have had no more problems with ES2 compatibility since I've been using https://github.com/Terr/django-haystack/commits/es2-integration-branch .

Currently using its latest commit ( 3d5f03ab676c132cdc59d01e9eaec4a857d169af ) in production.

**Comment by SalahAdDin** [comment] 2016-08-09 06:10
I have the same problem now, i'm working with `django-oscar` and `elasticsearch 2.3.5` and i have this bug:
```bash
Failed to query Elasticsearch using '(category:(Rose AND designs AND > AND Hijabs) OR category:(Rose AND designs AND > AND Hijabs AND > AND Bonetes AND & AND Tocados) OR category:(Rose AND designs AND > AND Hijabs AND > AND Bufandas) OR category:(Rose AND designs AND > AND Hijabs AND > AND Turbantes) OR category:(Rose AND designs AND > AND Hijabs AND > AND Chal) OR category:(Rose AND designs AND > AND Hijabs AND > AND Cubrecuellos AND & AND Cubrebrazos) OR category:(Rose AND designs AND > AND Superior) OR category:(Rose AND designs AND > AND Superior AND > AND Túnicas) OR category:(Rose AND designs AND > AND Vestidos) OR category:(Rose AND designs AND > AND Vestidos AND > AND Vestidos) OR category:(Rose AND designs AND > AND Vestidos AND Talla AND Grande) OR category:(Rose AND designs AND > AND Vestidos AND Talla AND Grande AND > AND Vestidos AND Talla AND Grande) OR category:(Rose AND designs AND > AND Inferiores) OR category:(Rose AND designs AND > AND Inferiores AND > AND Faldas) OR category:(Rose AND designs AND > AND Ropa AND de AND Calle) OR category:(Rose AND designs AND > AND Ropa AND de AND Calle AND > AND Abayas) OR category:(Rose AND designs AND > AND Ropa AND de AND Calle AND > AND Sobretodos AND & AND abrigos) OR category:(Rose AND designs AND > AND Ropa AND de AND Calle AND > AND Chaquetas) OR category:(Rose AND designs AND > AND Deportivos) OR category:(Rose AND designs AND > AND Deportivos AND > AND Vestidos AND de AND baño AND de AND cuerpo AND completo) OR category:(Rose AND designs AND > AND Deportivos AND > AND Vestidos AND de AND baño AND semi AND descubiertos) OR category:(Rose AND designs AND > AND Deportivos AND > AND Chándales) OR category:(Rose AND designs AND > AND Vestidos AND de AND Noche) OR category:(Rose AND designs AND > AND Vestidos AND de AND Noche AND > AND Vestidos AND de AND Noche AND Musulmanes) OR category:(Rose AND designs AND > AND Vestidos AND de AND Noche AND > AND Trajes AND de AND Noche) OR category:(Rose AND designs AND > AND Vestidos AND de AND Noche AND > AND Pijamas) OR category:(Rose AND designs))': TransportError(400, 'search_phase_execution_exception', 'failed to parse search source. unknown search element [facets]')
Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/haystack/backends/elasticsearch_backend.py", line 524, in search
    _source=True)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 548, in search
    doc_type, '_search'), params=params, body=body)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'failed to parse search source. unknown search element [facets]')
Failed to query Elasticsearch using '(category:(Rose AND designs AND > AND Hijabs) OR category:(Rose AND designs AND > AND Hijabs AND > AND Bonetes AND & AND Tocados) OR category:(Rose AND designs AND > AND Hijabs AND > AND Bufandas) OR category:(Rose AND designs AND > AND Hijabs AND > AND Turbantes) OR category:(Rose AND designs AND > AND Hijabs AND > AND Chal) OR category:(Rose AND designs AND > AND Hijabs AND > AND Cubrecuellos AND & AND Cubrebrazos) OR category:(Rose AND designs AND > AND Superior) OR category:(Rose AND designs AND > AND Superior AND > AND Túnicas) OR category:(Rose AND designs AND > AND Vestidos) OR category:(Rose AND designs AND > AND Vestidos AND > AND Vestidos) OR category:(Rose AND designs AND > AND Vestidos AND Talla AND Grande) OR category:(Rose AND designs AND > AND Vestidos AND Talla AND Grande AND > AND Vestidos AND Talla AND Grande) OR category:(Rose AND designs AND > AND Inferiores) OR category:(Rose AND designs AND > AND Inferiores AND > AND Faldas) OR category:(Rose AND designs AND > AND Ropa AND de AND Calle) OR category:(Rose AND designs AND > AND Ropa AND de AND Calle AND > AND Abayas) OR category:(Rose AND designs AND > AND Ropa AND de AND Calle AND > AND Sobretodos AND & AND abrigos) OR category:(Rose AND designs AND > AND Ropa AND de AND Calle AND > AND Chaquetas) OR category:(Rose AND designs AND > AND Deportivos) OR category:(Rose AND designs AND > AND Deportivos AND > AND Vestidos AND de AND baño AND de AND cuerpo AND completo) OR category:(Rose AND designs AND > AND Deportivos AND > AND Vestidos AND de AND baño AND semi AND descubiertos) OR category:(Rose AND designs AND > AND Deportivos AND > AND Chándales) OR category:(Rose AND designs AND > AND Vestidos AND de AND Noche) OR category:(Rose AND designs AND > AND Vestidos AND de AND Noche AND > AND Vestidos AND de AND Noche AND Musulmanes) OR category:(Rose AND designs AND > AND Vestidos AND de AND Noche AND > AND Trajes AND de AND Noche) OR category:(Rose AND designs AND > AND Vestidos AND de AND Noche AND > AND Pijamas) OR category:(Rose AND designs))': TransportError(400, 'search_phase_execution_exception', 'failed to parse search source. unknown search element [facets]')
Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/haystack/backends/elasticsearch_backend.py", line 524, in search
    _source=True)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 548, in search
    doc_type, '_search'), params=params, body=body)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'failed to parse search source. unknown search element [facets]')
```

@Mibou I'll try use your version.

**Comment by Mibou** [comment] 2016-08-09 07:34
Actually @SalahAdDin , everything seems to be fixed in trunk since https://github.com/django-haystack/django-haystack/releases/tag/v2.5.0

**Comment by SalahAdDin** [comment] 2016-08-09 22:15
But, i have the latest `django-haystack` version: `2.5.0`, and it doesn't works!

**Comment by BitcoinKing** [comment] 2016-10-02 22:55
Same problem as @SalahAdDin during facets setup from docs https://django-haystack.readthedocs.io/en/v2.5.0/faceting.html/ Also tried https://github.com/joaojunior/django-haystack/tree/es2_refactoring

Can anyone point the right django-haystack that works with Django 1.8.12, ES 2.4.1 ?

**Comment by acdha** [comment] 2016-10-03 14:40
@BitcoinKing See https://django-haystack.readthedocs.io/en/latest/installing_search_engines.html#elasticsearch. We're still looking for volunteers who want to work on ElasticSearch 2. #1391 would be a good place to start.

**Comment by BitcoinKing** [comment] 2016-10-03 15:04
@acdha i have it already installed and working. I was able setup elastic 1.7.3 with haystack 2.5.0 - with facets. So, documentation is obsolete

**Comment by acdha** [comment] 2016-10-03 15:05
@BitcoinKing your previous comment said you were using ElasticSearch 2.x, which is correctly documented as not being supported. 1.7 is supported.

**Comment by BitcoinKing** [comment] 2016-10-03 15:40
@acdha sorry, now i see this sentence "ElasticSearch 2.x is not supported yet, if you would like to help, please see #1247." that is pointed to this thread). So continue using 1.7.3

**Comment by SalahAdDin** [comment] 2016-10-03 23:16
But, will haystack support elastic 2.x.x soon?

**Comment by NDevox** [comment] 2016-12-06 11:27
For those interested I ported the current elasticsearch engine over to 2.X. I haven't managed to get it working with 5.x yet.

You can find it here: https://pypi.python.org/pypi/elasticsearch2-haystack

It should work for all versions up to 2.4 but it isn't perfect as it essentially patches 2.x to look like 1.x.

From what I've heard there is someone working on a newer backend which is hopefully optimised for the latest releases of ES which this isn't as far as I'm concerned. So I'm not going to make a PR - I'm just making it available until there is a better replacement.

We've tested it at our work on Django-Oscar and it works just fine right now.

**Comment by SalahAdDin** [comment] 2016-12-17 18:33
Very hard!

**Comment by NDevox** [comment] 2016-12-17 18:55
@SalahAdDin what is hard?

**Comment by SalahAdDin** [comment] 2016-12-26 11:20
@NDevox make 5.x.x integration.

**Closed** 2017-01-02 21:00 UTC

**Comment by NDevox** [comment] 2017-01-02 21:02
@acdha worth keeping open until released?

**Comment by acdha** [comment] 2017-01-02 21:07
@NDevox I was planning to do that tomorrow

**Comment by acdha** [comment] 2017-01-04 15:43
I just uploaded v2.6.0 to PyPI:

https://django-haystack.readthedocs.io/en/v2.6.0/changelog.html#v2-6-0-2017-01-02 
https://pypi.python.org/pypi/django-haystack/2.6.0
