### ISSUE TITLE
EmptySearchQuerySet with Solr

### ISSUE THREAD

**Issue by marcosschroh** [django-haystack/django-haystack#1311] opened 2016-02-16 17:11 UTC
I am using Solr and when I try to run a SearchQuerySet using the filter field__in=list and the list is empty, solr crash. I think that haystack should return an EmptySearchQuerySet.

**Comment by acdha** [comment] 2016-02-16 17:44
Duplicate of #318

**Closed by acdha** 2016-02-16 17:44 UTC
